### ISSUE TITLE
Error on parssing configuration file in sublime 3, comma problem?

### ISSUE THREAD

**Issue by mvofreire** [NoxArt/SublimeText2-FTPSync#221]
Error on parssing configuration file in sublime 3, comma problem

![captura de tela 3](https://cloud.githubusercontent.com/assets/4127341/12795907/1045be76-ca9b-11e5-86a9-9f0e1d384b32.png)

**Comment by NoxArt** [comment]
Hi,
as in the referenced case - what OS and Sublime version do you have?
If you change "debug_json" in Preferences > Package Settings > FTPSync > Settings - Default to true, restart Sublime and try to do an action with FTPSync, can you post what is in the console after message Debug JSON: ? (you can clear out password)

Also you can try simplifying the settings file as much as possible, even just replace the values, so that maybe it won't connect successfully, but at least be able to process the settings file
If it doesn't work, can you post it here? Without a password and other credentials of course

Thank you

**Comment by mvofreire** [comment]
Tanks @NoxArt issue resolved

https://github.com/NoxArt/SublimeText2-FTPSync/issues/202
