### ISSUE TITLE
sync_down_on_open not working for me as expected.

### ISSUE THREAD

**Issue by VinayKadalagi** [NoxArt/SublimeText2-FTPSync#227]
"type": "sftp",
    "save_before_upload": true,
    "upload_on_save": true,
    "sync_down_on_open": true,
    "sync_skip_deletes": false,
    "sync_same_age": true,
    "confirm_downloads": false,
    "confirm_sync": true,
    "confirm_overwrite_newer": false,

Above are my sftp-config.json settings. 
sync_down_on_open is true but it is not working for me.
I changed the remote file and then opened the previously synced local file. I expected local file to get updated but i received "No Operations to perform" and the file is not downloaded and synced. Please let me know if this is really an issue.

PS: I am using sftp_flags with proxy command. I am accessing actual server via an intermediate server (jump host). Other features are working fine...

**Comment by NoxArt** [comment]
Hi,
I'm afraid this repository is for a different plugin (FTPSync) than you are using (probably SFTP)?

FTPSync does not even support "sftp" as stated in the readme https://github.com/NoxArt/SublimeText2-FTPSync
It uses ftpsync.settings config file instead of sftp-config.json etc. and none of these options...
